// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import fs from "fs";
import path from "path";

const loadEnv = (filename: string) => {
  try {
    const envPath = path.resolve(process.cwd(), filename);
    if (fs.existsSync(envPath)) {
        const envFile = fs.readFileSync(envPath, "utf-8");
        const match = envFile.match(/DATABASE_URL=["']?(.*?)["']?$/m);
        if (match) {
            process.env.DATABASE_URL = match[1].trim();
            console.log(`Loaded DATABASE_URL manually from ${filename}`);
            return true;
        }
    }
  } catch (e) {
    console.warn(`Failed to manually load ${filename}`, e);
  }
  return false;
};

if (!process.env.DATABASE_URL) {
  if (!loadEnv(".env.local")) {
    loadEnv(".env");
  }
}

if (!process.env.DATABASE_URL) {
  const alt = process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL;
  if (alt) {
    process.env.DATABASE_URL = alt;
    console.log("Using fallback DATABASE_URL from POSTGRES_PRISMA_URL/POSTGRES_URL");
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
